theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
title: Plamo Social Hub
author: plamo.social
description: Plamo Social Hub is an informational site tied to plamo.social, a plastic modeling enthusiast Mastodon instance in the Fediverse.
lang: en
locale: en_US
url: "https://hub.plamo.social"
git_web_base: https://github.com/plamo-social/hub/blob/HEAD/
baseurl: ""
permalink: :title

# Theme Config
color_scheme: dark
search_enabled: true
heading_anchors: true
aux_links:
  "Back to plamo.social": https://plamo.social
aux_links_new_tab: false
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 Plamo Social, LLC. Distributed by an <a href=\"https://github.com/plamo-social/hub.plamo.social/tree/main/LICENSE\">MIT license.</a>"

nav_external_links:
  - title: System Status
    url: https://status.plamo.social
    hide_icon: false

callouts:
  important:
    title: Important!
    color: blue

# RSS feeds
feed:
  posts_limit: 20
